events {}

http {
    server {
        listen 80;

        location /api/ {
            proxy_pass http://flask_api:5000/api/;
            proxy_set_header Host $host;
        }

        location / {
            return 200 'nginx is running';
            add_header Content-Type text/plain;
        }
    }
}
